name: Team Approval CI
on:
  pull_request_review:
    branches:
      - develop
      - main
  workflow_dispatch: [ ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label-when-approved:
    runs-on:
      - self-hosted
      - ubuntu-latest
