name: Team Approval CI
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label-when-approved:
    runs-on: ubuntu-latest

    steps:
      - name: label-approved-action
        uses: AnandChowdhary/label-approved-action@v1.0.0
