name: Team Approval CI
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
          REMOVE_LABEL: "awaiting%20review"

      - if: github.base_ref != 'develop'
        name: runs if is not the develop branch
        run: |
          echo Hello from ${{ github.base_ref }}
