name: Team Approval CI
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "2"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
          REMOVE_LABEL: "awaiting%20review"
