# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI  - feature branches

on:
  push:
    # Ejecutar en todas las ramas
    branches: []
    branches-ignore:
      - main
      - develop

  pull_request:
    # Ejecutar en todas las ramas
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install and build webpack
        run: |
          npm ci
          npm install
          npm run build --if-present
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@master
        with:
          # Artifact name
          name: webpack artifacts # optional, default is artifact

          # A file, directory or wildcard pattern that describes what to upload
          path: public/

  test:
    runs-on: ubuntu-latest
    needs: build


    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Download the Artifacts
        uses: actions/download-artifact@master
        with:
          # Artifact name
          name: webpack artifacts # optional, default is artifact

          # A file, directory or wildcard pattern that describes what to upload
          path: public
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install and test
        run: |
          npm ci
          npm install
          npm test
        env:
          ci: true
